import { colors, fonts } from '../variables'

export const darkTheme = {
    name: 'DARK',
    primary: colors.primary,
    secondary: colors.secondary,
    // #BACKGROUND
    mainBg: '#272727',
    secondaryBg: '#2f2f2f',
    tertiaryBg: '#e4e4e4',
    overlay: '#000000a8',
    // #FONTS
    fontStack: fonts.vpFontFamily,
    buttonFontSize: '16px',
    // #HEADINGS
    heading: 'lightgrey',
    // #TEXT
    primaryText: 'lightgrey',
    // #BUTTONS
    primaryButtonBg: '#337b3b',
    primaryButtonBorder: colors.vpGreen,
    primaryButtonText: '#ffffff',
    primaryButtonLoadingBg: colors.vpGreen,
    secondaryButtonBg: 'transparent',
    secondaryButtonBorder: 'lightgrey',
    secondaryButtonText: 'lightgrey',
    secondaryButtonHvr: 'lightgrey',
    secondaryButtonTextHvr: colors.bgSecondary,
    secondaryButtonLoadingBg: colors.vpGreen,
    tertiaryButtonBg: '#008490',
    tertiaryButtonText: colors.white,
    tertiaryButtonLoadingBg: colors.vpAquaBlue,
    buttonLoading: colors.white,
    // #BORDERS
    borderColor: 'lightgrey',
    borderRadius: '5px',
    // #FOCUS
    focus: colors.grey.b,
    // #LABELS
    labelColor: 'lightgrey',
    // #INPUT
    inputBg: colors.grey.e,
    inputBorder: colors.grey.e,
    inputText: colors.white,
    // #MODAL
    modalBg: '#282828',
    modalTitle: '#eeeeee',
    modalCloseIcon: '#eeeeee',
    modalCloseIconHvr: 'lightgrey',
    modalCloseHvr: '#3f3f3f',
    modalCloseAct: '#eeeeee',
    modalCloseIconAct: '#575757',
    // #DETAILSBOX
    detailsBg: '#353535',
    detailsHeading: '#bdbdbd',
    // #TOGGLE
    toggleBg: '#616161',
    toggledBg: '#4f9257',
    toggleCircle: colors.white,
    // #TOOLTIP
    tooltipBg: '#171717',
    tooltipText: colors.white,
    // #OPTIONSMENU
    optionsMenuBg: colors.white,
    optionsMenuBorder: '#dadada',
}
